language: dart
dist: xenial
addons:
  apt:
    packages:
    - lib32stdc++6
install:
- git clone https://github.com/flutter/flutter.git -b beta
- ./flutter/bin/flutter doctor
script:
- flutter build apk --debug
cache:
  directories:
  - $HOME/.pub-cache
